### ISSUE TITLE
Both of them should be of same color(text)

### ISSUE THREAD

**Issue by naveesha-vayuz** [rgnarok/Flutterwebsite#16]
![image](https://github.com/rgnarok/Flutterwebsite/assets/121479721/d96b7135-1866-44e3-a215-2141a382ceaf)

**Comment by milivayuz** [comment]
@naveesha-vayuz kindly check and update the pointer status

**Comment by naveesha-vayuz** [comment]
not updated

**Comment by naveesha-vayuz** [comment]
Flutter vs tech stack
