### ISSUE TITLE
Need to change the background image to that of something related to AI or Jarvisy.  

### ISSUE THREAD

**Issue by naveesha-vayuz** [rgnarok/Flutterwebsite#25]
![image](https://github.com/rgnarok/Flutterwebsite/assets/121479721/beb82035-c5a4-43b9-bf10-e82cee3bea7e)
 
 
 Also the mobile mockup is not covering the screen properly

**Comment by rahulmvayuz** [comment]
![image](https://github.com/rgnarok/Flutterwebsite/assets/164298543/87c6cca1-f9ee-4f5f-86b4-4dca2041a011)
