### ISSUE TITLE
Techno> Author name missing in details

### ISSUE THREAD

**Issue by Anupriyabanger** [rgnarok/Flutterwebsite#3]
![image](https://github.com/rgnarok/Flutterwebsite/assets/109590553/578f9242-a6a4-4cc6-81ff-63cde637bcd9)
![image](https://github.com/rgnarok/Flutterwebsite/assets/109590553/d0c0f071-b747-4ace-a79f-16281d4b3ef0)

**Comment by milivayuz** [comment]
website updated
