### ISSUE TITLE
Website Details > Favicon missing 

### ISSUE THREAD

**Issue by vinayak-vayuz** [rgnarok/Flutterwebsite#83]
<img width="28" alt="image" src="https://github.com/rgnarok/Flutterwebsite/assets/128778447/1bb31d74-e1fa-4ed9-af58-c7a8af129181">

**Comment by rahulmvayuz** [comment]
![image](https://github.com/rgnarok/Flutterwebsite/assets/164298543/4868040b-1457-4600-9a7f-b868cc242038)
