### ISSUE TITLE
Overall > Readability issue font size is too small

### ISSUE THREAD

**Issue by vinayak-vayuz** [rgnarok/Flutterwebsite#85]

**Comment by rahulmvayuz** [comment]
![image (3)](https://github.com/rgnarok/Flutterwebsite/assets/164298543/c7b99cc3-4bc3-48bb-bd9d-9e408bc3b392)
![image (2)](https://github.com/rgnarok/Flutterwebsite/assets/164298543/2d83c5f3-2874-4cdc-a59b-4d239edc3d84)
![image (1)](https://github.com/rgnarok/Flutterwebsite/assets/164298543/340647c7-0961-43cb-8cbe-72431bd7df13)
![image](https://github.com/rgnarok/Flutterwebsite/assets/164298543/2cceb57d-f32b-4a6d-8bc4-4240819fb224)
